FetchContent_Declare(
  LIBUV
  URL https://mirrors.tuna.tsinghua.edu.cn/gentoo/distfiles/libuv-1.42.0.tar.gz
  URL_HASH SHA1=d1750da0846b91289bcd4f0128ebcaea6c70a272


  CMAKE_CACHE_ARGS
  -DCMAKE_INSTALL_PREFIX:STRING=${CMAKE_BINARY_DIR}/3rdparty/
  -DCMAKE_C_COMPILER:STRING=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_COMPILER:STRING=${CMAKE_CXX_COMPILER}
  -DCMAKE_CXX_FLAGS:STRING=${BUILD_WITHOUT_CXX11_FLAGS}
  -DBUILD_TESTING:BOOL=OFF
)
FetchContent_MakeAvailable(LIBUV)
